environment:
  window_size: [224, 224]
  traffic_density: 0.10
  stack_size: 4
  accident_prob: 0.1
  map: "CCCCCCCCCCCCCCC"
  num_scenarios: 200
simulation:
  simulations_count: 4
  show_view: True #currently works only in .collect_frames()
seed: 1
algorithm:
  learning_rate: 8e-4
  batch_size: 512 # x num_envs
  minibatch_size: 512
  n_epochs: 5
  gamma: 0.99
  gae_lambda: 0.95
training:
  steps: 1e5
mlflow:  
  tracking_uri: http://192.168.8.121:5000
  experiment_name: MetaDrive ViT testing
